// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyCopyrightAttribute("Roman Provaznik")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyCopyright = "Roman Provaznik"
